"""add_detected_cnt

Revision ID: 27e734b86399
Revises: f989f900cbcb
Create Date: 2024-06-26 01:45:43.065424

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27e734b86399'
down_revision = 'f989f900cbcb'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    try:
        globals()["upgrade_%s" % engine_name]()
    except KeyError:
        pass


def downgrade(engine_name: str) -> None:
    try:
        globals()["downgrade_%s" % engine_name]()
    except KeyError:
        pass





def upgrade_projects() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('detected_cnt', sa.Integer(), nullable=True, default=None))
    op.add_column('videos', sa.Column('detected_cnt', sa.Integer(), nullable=True, default=None))
    # ### end Alembic commands ###


def downgrade_projects() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'detected_cnt')
    op.drop_column('videos', 'detected_cnt')
    # ### end Alembic commands ###


def upgrade_users() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

