"""add_frame_content_idx

Revision ID: f989f900cbcb
Revises: e73e6a1a47d9
Create Date: 2024-06-25 17:56:28.012743

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f989f900cbcb'
down_revision = 'e73e6a1a47d9'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    try:
        globals()["upgrade_%s" % engine_name]()
    except KeyError:
        pass


def downgrade(engine_name: str) -> None:
    try:
        globals()["downgrade_%s" % engine_name]()
    except KeyError:
        pass





def upgrade_projects() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # добавляем индекс на поле content_id
    op.create_index('idx_frames_content_id', 'frames', ['content_id'])
    op.create_index('idx_frame_markup_frame_id', 'frame_markup', ['frame_id'])

    # ### end Alembic commands ###


def downgrade_projects() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # удаляем индекс
    op.drop_index('idx_frame_markup_frame_id', table_name='frame_markup')
    op.drop_index('idx_frames_content_id', table_name='frames')

    # ### end Alembic commands ###


def upgrade_users() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

